import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Page: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      What uppp
    </div>
  );
};

export default Page;
