export const teamInfo = [
  {
    Name: "Greeshma Medam",
    Responsibility: "Discord Moderator",
    AboutMe:
      "I am an enthusiastic student with a keen interest in Web development and communities.",
    emailId: "greeshma290303@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/m-greeshma/",
    instagramUrl: "https://www.instagram.com/medam_greeshma/",
    twitterUrl: "https://twitter.com/GreeshmaMedam",
    githubUrl: "https://github.com/Greeshma2903",
    websiteUrl: undefined,
    image: "https://i.imgur.com/MfjMbhx.png",
  },
  {
    Name: "Nimish Jain",
    Responsibility: "Discord Moderator",
    AboutMe:
      "I am a full-stack developer trying to learn anything that comes my way.",
    emailId: "nimishjain100701@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/nimishjn/",
    instagramUrl: "https://www.instagram.com/nimishjain_/",
    twitterUrl: "https://twitter.com/nimishjain_",
    githubUrl: "https://github.com/nimishjn",
    websiteUrl: "https://www.nimish-jain.com/",
    image: "https://i.imgur.com/GQ1P6Y8.png",
  },
  {
    Name: "Ankita Sahu",
    Responsibility: "Event Organizer",
    AboutMe: "I love hosting and organizing events, hailing from Bhubaneswar.",
    emailId: "ankita.sahuof1@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/ankita-sahu-540920201/",
    instagramUrl: "https://www.instagram.com/zin1nia/",
    twitterUrl: "https://twitter.com/asahu_dev",
    githubUrl: "https://github.com/SAHU-01",
    websiteUrl: undefined,
    image: "https://i.imgur.com/0bNtj78.png",
  },
  {
    Name: "Sarah Crossan",
    Responsibility: "Graphic Designer",
    AboutMe:
      "A graphic designer interested in tech; now an AWS Cloud Practioner, too.",
    emailId: "scrossanworks@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/sarah-crossan-861389a0/",
    instagramUrl: "https://www.instagram.com/sarah.crossan/?hl=en",
    twitterUrl: undefined,
    githubUrl: "https://github.com/HMthyl",
    websiteUrl: undefined,
    image: "https://i.imgur.com/jISkV8Y.png",
  },
  {
    Name: "Macy So",
    Responsibility: "Opportunities Team",
    AboutMe: "I am a college sophomore at Boston Univesrity, aspired to become a PM or SWE",
    emailId: "macyso12@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/macyso/",
    instagramUrl: "https://www.instagram.com/macie._.here/",
    twitterUrl: undefined,
    githubUrl: "https://github.com/macyso12 ",
    websiteUrl: undefined,
    image: "https://i.imgur.com/AK86kix.png",
  },
  {
    Name: "Falguni Sarkar",
    Responsibility: "Event Organizer",
    AboutMe: "I’m currently learning stuff to be a Full-Stack Web Developer!",
    emailId: "falgunisarkar526@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/falgunisarkar",
    instagramUrl: "https://www.instagram.com/isshefalguni/",
    twitterUrl: "https://twitter.com/isshefalguni",
    githubUrl: "https://github.com/lostgirljourney",
    websiteUrl: undefined,
    image: "https://i.imgur.com/WCpRB2E.png",
  },
  {
    Name: "Aniruddha Das",
    Responsibility: "Video Editor",
    AboutMe:
      "Web Developer | UI/UX Designer",
    emailId: "aniruddha.das.852@gmail.com",
    linkedinUrl: "https://www.linkedin.com/mwlite/in/aniruddhadas852",
    instagramUrl: "https://www.instagram.com/_aniruddha852_/",
    twitterUrl: "https://twitter.com/isthatAniruddha",
    githubUrl: "https://github.com/OctoplusNinja",
    websiteUrl: undefined,
    image: "https://i.imgur.com/FpRudKG.png",
  },
  {
    Name: "Shivanshi Saxena",
    Responsibility: "Content Writer",
    AboutMe:
      "I am a front-end developer and Designer based in Delhi",
    emailId: "shivanshi.saxena2@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/shivanshi-saxena12/",
    instagramUrl: "https://instagram.com/whatshivanshi",
    twitterUrl: "https://twitter.com/whatshivanshi",
    githubUrl: "https://github.com/shivanshi-s",
    websiteUrl: undefined,
    image: "https://i.imgur.com/uelXDvr.png",
  },
  {
    Name: "Shriram Parab",
    Responsibility: "Graphic Designer",
    AboutMe:
      "I am a generalist who is exploring the metaverse.",
    emailId: "shriram.parab18@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/shriparab",
    instagramUrl: undefined,
    twitterUrl: undefined,
    githubUrl: undefined,
    websiteUrl: undefined,
    image: "https://i.imgur.com/7oy0Fak.png",
  },
  {
    Name: "M. Gokul Raj",
    Responsibility: "Graphic Designer",
    AboutMe:
      "I am a Graphic designer and an aspiring Electronics Engineer.",
    emailId: "mgokul2k@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/m-gokul-raj-3a1603184",
    instagramUrl: "https://www.instagram.com/____chilly____/",
    twitterUrl: undefined,
    githubUrl: undefined,
    websiteUrl: undefined,
    image: "https://i.imgur.com/7ZpXAga.png",
  },
  {
    Name: "Fuzail Danish Khan",
    Responsibility: "Graphic Designer",
    AboutMe:
      "I am a Graphic Designer and a pseudo Web developer, based in Goa.",
    emailId: "www.fuzailkhan360@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/fuzail-khan-4794a11a4",
    instagramUrl: "https://www.instagram.com/johnny_ka_fan",
    twitterUrl: undefined,
    githubUrl: undefined,
    websiteUrl: undefined,
    image: "https://i.imgur.com/ybOfuPf.png",
  },
  {
    Name: "Chetna Grover",
    Responsibility: "Graphic Designer",
    AboutMe:
      "Front-end Web Developer | Creative Designer ( UI and Graphics )",
    emailId: "chetugrover@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/chetnagrover/",
    instagramUrl:
      "https://www.instagram.com/chetna_grover3120/?igshid=1b27kmwxyv5j7",
    twitterUrl: undefined,
    githubUrl: "https://github.com/chetnagrover00",
    websiteUrl: undefined,
    image: "https://i.imgur.com/PFCbsJS.png",
  },
  {
    Name: "Satish Baiginkar",
    Responsibility: "Content Writer",
    AboutMe: "In my world, \"Debugging\" is like being the detective in a crime drama where I m the murderer as well.",
    emailId: "Emperorsupreme0011@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/satish-b-292ab81b2/",
    instagramUrl: "https://www.instagram.com/baiginkarsatish/",
    twitterUrl: undefined,
    githubUrl: "https://github.com/emperorsupremesatish",
    websiteUrl: undefined,
    image: "https://i.imgur.com/TkLZnMg.png",
  },
  {
    Name: "Shrutika Gawas",
    Responsibility: "Event Organizer",
    AboutMe:
      "I'm an aspiring front-end developer who's always curious and eager to learn more.",
    emailId: "shrutikagawas26@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/shrutika-g-40829910b",
    instagramUrl: "https://www.instagram.com/shrutikagawas/",
    twitterUrl: "https://twitter.com/ShrutikaGawas",
    githubUrl: "https://github.com/ShrutikaGawas",
    websiteUrl: undefined,
    image: "https://i.imgur.com/xx3h8Fa.png",
  },
  {
    Name: "Harshjot Singh",
    Responsibility: "Event Organizer",
    AboutMe:
      "I am an enthusiast innovator with a belief to explore my potential and acquire skills.",
    emailId: "harshjot1469@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/harshjot-singh/",
    instagramUrl: "https://instagram.com/_.harshjot._",
    twitterUrl: undefined,
    githubUrl: "http://github.com/Harsh-jot",
    websiteUrl: undefined,
    image: "https://i.imgur.com/g5Z3oLz.png",
  },
  {
    Name: "Muthu Annamalai Venkatachalam",
    Responsibility: "Opportunities Team",
    AboutMe:
      "I am a Technical writer and an aspiring Web Developer who loves community.",
    emailId: "muthuannamalai2002@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/muthu-annamalai/",
    instagramUrl: "https://www.instagram.com/thepseudocoders/",
    twitterUrl: "https://twitter.com/muthuannamalai_",
    githubUrl: "https://github.com/muthuannamalai12",
    websiteUrl: undefined,
    image: "https://i.imgur.com/h1qpLIK.png",
  },
  {
    Name: "Nandani Paliwal",
    Responsibility: "Opportunities Team",
    AboutMe:
      "Sophomore | Front-end Web Developer | Community enthusiastic",
    emailId: "paliwalnandani12@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/nandani-paliwal-979a2120b",
    instagramUrl: "https://instagram.com/paliwal.nandani",
    twitterUrl: "https://twitter.com/Nandani4678",
    githubUrl: "https://github.com/Nandani-Paliwal",
    websiteUrl: undefined,
    image: "https://i.imgur.com/HvFttrI.png",
  },
  // {
  //   Name: "Trusha Neogi",
  //   Responsibility: "Graphic Designer",
  //   AboutMe:
  //     "I am a Technical writer and an aspiring Web Developer who loves community",
  //   emailId: "trushaneogi05@gmail.com",
  //   linkedinUrl: "https://www.linkedin.com/in/trusha-neogi-6a69bb191",
  //   instagramUrl: "https://www.instagram.com/tuuushaa/",
  //   twitterUrl: "https://twitter.com/trusha_0503",
  //   githubUrl: "https://github.com/trushaneogi",
  //   websiteUrl: undefined,
  //   image: "https://i.imgur.com/EGtzqb9.png",
  // },
];

export const developersInfo = [
  {
    Name: "Devraj Chatribin",
    Responsibility: "Founder & Lead Designer",
    AboutMe:
      "I use my creativity to create intruiging designs and building engaging communitites.",
    emailId: "devrajchatribin9978@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/devraj-chatribin/",
    instagramUrl: "https://www.instagram.com/designfordev",
    twitterUrl: "https://twitter.com/devrajchatribin",
    githubUrl: "https://github.com/DevrajDC",
    websiteUrl: "http://devrajchatribin.co/",
    image: "https://i.imgur.com/EGtzqb9.png",
  },
  {
    Name: "Jaagrav Seal",
    Responsibility: "Frontend Developer",
    AboutMe:
      "I am a Front end web developer",
    emailId: "jaagravseal03@gmail.com",
    linkedinUrl: "https://linkedin.com/in/Jaagrav",
    instagramUrl: undefined,
    twitterUrl: "https://twitter.com/xJaagrav",
    githubUrl: "https://github.com/Jaagrav",
    websiteUrl: "https://xjaagrav.netlify.app/",
    image: "https://i.imgur.com/BEcLYLl.png",
  },
  {
    Name: "Shridhar Kamat",
    Responsibility: "Frontend Developer",
    AboutMe:
      "Web Developer",
    emailId: "shridharkamat10@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/shridhar-kamat-1015a41bb/",
    instagramUrl: undefined,
    twitterUrl: "https://twitter.com/shridhar_kdev",
    githubUrl: "https://github.com/Shridhar-dev/",
    websiteUrl: "https://shridharkamat.dev/",
    image: "https://i.imgur.com/CmacNSS.png",
  },
  {
    Name: "Aman Tyagi",
    Responsibility: "UI/UX Designer",
    AboutMe:
      "I'm a UI/UX Designer and Front-end Web Developer, based in Ghaziabad, India.",
    emailId: "amantyagi994@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/aman--tyagi/",
    instagramUrl: "https://instagram.com/amantyagi998",
    twitterUrl: "https://twitter.com/aman__tyagi",
    githubUrl: "https://github.com/amantyagi994",
    websiteUrl: "https://aman-tyagi.web.app/",
    image: "https://i.imgur.com/qgODs8u.png",
  },
  {
    Name: "Greeshma Medam",
    Responsibility: "Frontend Developer",
    AboutMe:
      "I am an enthusiastic student with a keen interest in Web development and communities",
    emailId: "greeshma290303@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/m-greeshma/",
    instagramUrl: "https://www.instagram.com/medam_greeshma/",
    twitterUrl: "https://twitter.com/GreeshmaMedam",
    githubUrl: "https://github.com/Greeshma2903",
    websiteUrl: undefined,
    image: "https://i.imgur.com/MfjMbhx.png",
  },
  {
    Name: "Swaroop Rajwal",
    Responsibility: "Frontend Developer",
    AboutMe:
      "I am a computer science and fitness enthusiast.",
    emailId: "swaroop.rajwal18@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/swaroop-rajwal-a606761b5/",
    instagramUrl: "https://www.instagram.com/swaroop_rajwal/",
    twitterUrl: "https://twitter.com/RajwalSwaroop",
    githubUrl: "https://github.com/swaroop18122002",
    websiteUrl: undefined,
    image: "https://i.imgur.com/CXnjT1b.png",
  },
  {
    Name: "Nimish Jain",
    Responsibility: "Frontend Developer",
    AboutMe:
      "I am a full-stack developer trying to learn anything that comes his way.",
    emailId: "nimishjain100701@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/nimishjn/",
    instagramUrl: "https://www.instagram.com/nimishjain_/",
    twitterUrl: "https://twitter.com/nimishjain_",
    githubUrl: "https://github.com/nimishjn",
    websiteUrl: "https://www.nimish-jain.com/",
    image: "https://i.imgur.com/GQ1P6Y8.png",
  },
];
